# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d23e377a1904c797a8d25be698fc24a6bfa057201a6cec95f0fdd583535764f7ef47797cf36e8518140e1881a8bd5c0720b44dfd076f29cb9e841ff0c62bc7

test:
  secret_key_base: e17334e271f2e68efe2ca02f54b81f100a542775784b7e558392d8f283dd0a798ebc709d4f25454b263231b6079e5f87301e35c33e4e4173f8306ce3817b4a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
